langeuage: go
go: '1.11'
os: linux
git:
   depth: 1

before_script:
- go install github.com/goadesign/goa
- go install github.com/goadesign/goa/goagen
- go get github.com/goadesign/goa/goagen/gen_app 
- go get github.com/goadesign/goa/goagen/gen_swagger
- go get github.com/goadesign/goa/goagen/gen_controlle
- make goa

jobs:
   include:
   - stage: test
     script:
     - make test

   - stage: build
     script:
     - echo build
   
   - stage: deploy
     script: 
     - echo deploy